version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - ELASTICSEARCH_SECURITY_AUTO_CONFIGURE=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  api:
    build: .
    depends_on:
      - postgres
      - redis
      - elasticsearch
    environment:
      POSTGRES_DSN: "host=postgres user=bloguser password=blogpass dbname=blogdb sslmode=disable"
      REDIS_ADDR: "redis:6379"
      ES_ADDR: "http://elasticsearch:9200"
    ports:
      - "8080:8080"

volumes:
  pgdata:
  esdata:
